version: "3.8"
services:
  airflow:
    image: apache/airflow:2.9.3
    container_name: airflow-fin
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AWS_REGION=ap-southeast-1
      - ATHENA_OUTPUT_S3=s3://fin-risk-observatory-joanne/athena_query_results/
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ../:/opt/airflow/project
      - ./sql:/opt/airflow/sql
      - ~/.aws:/home/airflow/.aws:ro
    ports:
      - "8081:8080"
    command: >
      bash -lc "airflow db init &&
                airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
                airflow webserver & airflow scheduler"

